-- {业务名}_{表作用} 表（PostgreSQL 14+）
-- 通用字段：id(bigint 雪花ID/DB序列兜底)、created_at、updated_at、created_by、updated_by
-- 布尔字段：is_xxx boolean
-- 小数：numeric(19,4)，禁止 float/double precision
-- 索引：uk_字段名、idx_字段名

-- 1. 建表
CREATE TABLE {table_name} (
  id          bigint        GENERATED BY DEFAULT AS IDENTITY,  -- 应用层插入雪花ID，DB序列兜底
  {业务字段...}
  created_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by  bigint        NOT NULL DEFAULT 0,
  updated_by  bigint        NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

-- 2. 注释
COMMENT ON TABLE  {table_name}              IS '{表注释}';
COMMENT ON COLUMN {table_name}.id           IS '主键（雪花ID）';
-- {业务字段注释...}
COMMENT ON COLUMN {table_name}.created_at   IS '创建时间';
COMMENT ON COLUMN {table_name}.updated_at   IS '更新时间';
COMMENT ON COLUMN {table_name}.created_by   IS '创建人 userId';
COMMENT ON COLUMN {table_name}.updated_by   IS '更新人 userId';

-- 3. 索引（按需选择）
-- CREATE UNIQUE INDEX uk_{table_name}_{唯一字段} ON {table_name} ({唯一字段});
-- CREATE INDEX idx_{table_name}_{查询字段} ON {table_name} ({查询字段});

-- 4. updated_at 表级兜底触发器（必须，每个库只需创建一次函数）
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_{table_name}_updated_at
BEFORE UPDATE ON {table_name}
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
