#!/usr/bin/env bash
# java-database/scripts/check-sql.sh
# 覆盖：DB-01~DB-05b、DB-06~DB-10、DB-12、DB-13、DB-15（rg 扫描 XML/SQL/Java 文件）
# 数据库：PostgreSQL 14+
# 用法：bash check-sql.sh [目标目录] [--files "file1 file2 ..."]

set -euo pipefail

TARGET="${1:-.}"
INCREMENTAL_FILES=()
if [[ "${1:-}" == "--files" ]]; then
  read -ra INCREMENTAL_FILES <<< "${2:-}"
  TARGET="."
fi

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

ERRORS=0
WARNINGS=0
print_error()   { echo -e "${RED}❌ [ERROR]${NC} $*"; ((ERRORS++)) || true; }
print_warning() { echo -e "${YELLOW}🟡 [WARN] ${NC} $*"; ((WARNINGS++)) || true; }
print_ok()      { echo -e "${GREEN}✅ $*${NC}"; }

run_rg() {
  local pattern="$1"; shift
  local flags=("$@")
  if [[ ${#INCREMENTAL_FILES[@]} -gt 0 ]]; then
    rg --no-heading -n "${flags[@]+"${flags[@]}"}" "$pattern" "${INCREMENTAL_FILES[@]}" 2>/dev/null || true
  else
    rg --no-heading -n "${flags[@]+"${flags[@]}"}" "$pattern" "$TARGET" 2>/dev/null || true
  fi
}

echo "============================================"
echo "  java-database / check-sql.sh  [PostgreSQL]"
echo "  扫描范围: $TARGET"
echo "============================================"

# DB-01  SELECT *（含 XML 和注解 SQL）
echo ""
echo "【DB-01】检查 SELECT *..."
HITS=$(run_rg 'SELECT\s+\*' -i -g '*.xml' -g '*.sql' -g '*.java' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "禁止 SELECT *，应明确列出所需字段：$line"
  done <<< "$HITS"
else
  print_ok "DB-01 通过"
fi

# DB-02  ${} SQL 拼接（SQL 注入风险）
echo ""
echo "【DB-02】检查 \${} SQL 拼接（SQL 注入风险）..."
HITS=$(run_rg '\$\{[^}]+\}' -g '*.xml' -g '*.java' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "禁止 \${} 拼接 SQL（SQL 注入风险），改用 #{}：$line"
  done <<< "$HITS"
else
  print_ok "DB-02 通过"
fi

# DB-03  无 WHERE 条件的 UPDATE/DELETE
echo ""
echo "【DB-03】检查无 WHERE 的 UPDATE/DELETE..."
HITS=$(run_rg '<(update|delete)[^>]*>[^<]*</(update|delete)>' -i -g '*.xml' -U || true)
if [[ -n "$HITS" ]]; then
  FILTERED=$(echo "$HITS" | grep -iv 'where\|<where>' || true)
  if [[ -n "$FILTERED" ]]; then
    while IFS= read -r line; do
      print_error "疑似无 WHERE 条件的 UPDATE/DELETE，存在全表操作风险：$line"
    done <<< "$FILTERED"
  else
    print_ok "DB-03 通过"
  fi
else
  print_ok "DB-03 通过"
fi

# DB-04a  SERIAL 类型（旧自增策略，应改用 GENERATED BY DEFAULT AS IDENTITY）
echo ""
echo "【DB-04a】检查 SERIAL / BIGSERIAL 类型（旧自增策略）..."
HITS=$(run_rg '\b(SERIAL|BIGSERIAL|SMALLSERIAL)\b' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "禁止 SERIAL/BIGSERIAL，主键应使用 bigint GENERATED BY DEFAULT AS IDENTITY：$line"
  done <<< "$HITS"
else
  print_ok "DB-04a 通过"
fi

# DB-04b  GENERATED ALWAYS AS IDENTITY（会拒绝外部写入，禁止使用）
echo ""
echo "【DB-04b】检查 GENERATED ALWAYS AS IDENTITY（禁止）..."
HITS=$(run_rg 'GENERATED\s+ALWAYS\s+AS\s+IDENTITY' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "禁止 GENERATED ALWAYS AS IDENTITY（会拒绝外部写入），应使用 GENERATED BY DEFAULT AS IDENTITY：$line"
  done <<< "$HITS"
else
  print_ok "DB-04b 通过"
fi

# DB-05  FLOAT/DOUBLE PRECISION 金额字段
echo ""
echo "【DB-05】检查 FLOAT/DOUBLE PRECISION 金额字段..."
HITS=$(run_rg '(amount|price|fee|money|salary|balance|cost)\s+[A-Z]*(FLOAT|DOUBLE\s+PRECISION|REAL)' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "金额字段禁止使用 FLOAT/DOUBLE PRECISION（精度丢失），改用 numeric(19,4)：$line"
  done <<< "$HITS"
else
  print_ok "DB-05 通过"
fi

# DB-06  缺少 COMMENT ON COLUMN 注释
echo ""
echo "【DB-06】检查缺少 COMMENT ON COLUMN 注释..."
# 找到有 CREATE TABLE 但没有对应 COMMENT ON COLUMN 的文件
HITS=$(run_rg 'CREATE\s+TABLE\b' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    FILE=$(echo "$line" | cut -d: -f1)
    if ! rg -q 'COMMENT\s+ON\s+COLUMN' -i "$FILE" 2>/dev/null; then
      print_warning "文件 $FILE 含 CREATE TABLE 但未找到 COMMENT ON COLUMN，字段注释可能缺失"
    fi
  done <<< "$HITS"
  # 若上面循环没有触发 warning，给一个统一的 OK
  if [[ $WARNINGS -eq 0 ]]; then
    print_ok "DB-06 通过"
  fi
else
  print_ok "DB-06 通过（无 SQL 文件）"
fi

# DB-07  逻辑删除字段非 is_deleted
echo ""
echo "【DB-07】检查逻辑删除字段命名（非 is_deleted）..."
HITS=$(run_rg '\b(deleted|is_delete|del_flag|delete_flag)\b' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "逻辑删除字段命名应统一为 is_deleted：$line"
  done <<< "$HITS"
else
  print_ok "DB-07 通过"
fi

# DB-08  字段/表名含驼峰（应全小写下划线）
echo ""
echo "【DB-08】检查字段/表名含驼峰..."
# PostgreSQL 中裸标识符会自动转小写，但双引号包裹的驼峰仍能生效，属于违规
HITS=$(run_rg '"[a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*"' -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "表名/字段名应全小写下划线命名，禁止驼峰（即使加双引号）：$line"
  done <<< "$HITS"
else
  print_ok "DB-08 通过"
fi

# DB-09  MySQL 专属语法残留（ENGINE / CHARSET / AUTO_INCREMENT）
echo ""
echo "【DB-09】检查 MySQL 专属语法残留..."
HITS=$(run_rg '\b(ENGINE\s*=|CHARSET\s*=|AUTO_INCREMENT|TINYINT|DATETIME)\b' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "发现 MySQL 专属语法，当前数据库为 PostgreSQL，请使用 PostgreSQL DDL：$line"
  done <<< "$HITS"
else
  print_ok "DB-09 通过"
fi

# DB-10  使用 json 类型而非 jsonb
echo ""
echo "【DB-10】检查 json 类型（应改用 jsonb）..."
HITS=$(run_rg '\bjson\b(?!\s*b)' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_warning "建议将 json 类型改为 jsonb（支持索引、查询效率更高）：$line"
  done <<< "$HITS"
else
  print_ok "DB-10 通过"
fi

# DB-12  普通索引命名不符合 idx_
echo ""
echo "【DB-12】检查普通索引命名规范（idx_）..."
HITS=$(run_rg 'CREATE\s+INDEX\s+(?!idx_)\w+' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "普通索引命名应为 idx_{table}_{col} 格式：$line"
  done <<< "$HITS"
else
  print_ok "DB-12 通过"
fi

# DB-13  唯一索引命名不符合 uk_
echo ""
echo "【DB-13】检查唯一索引命名规范（uk_）..."
HITS=$(run_rg 'CREATE\s+UNIQUE\s+INDEX\s+(?!uk_)\w+' -i -g '*.sql' || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_error "唯一索引命名应为 uk_{table}_{col} 格式：$line"
  done <<< "$HITS"
else
  print_ok "DB-13 通过"
fi

# DB-15  无 LIMIT 的 SELECT（全表扫描风险）
echo ""
echo "【DB-15】检查无 LIMIT 的 SELECT（全表扫描风险）..."
HITS=$(run_rg '<select[^>]*>(?:(?!LIMIT|limit|<\/select>).)*<\/select>' -g '*.xml' -U || true)
if [[ -n "$HITS" ]]; then
  while IFS= read -r line; do
    print_warning "XML mapper 中 SELECT 无 LIMIT 限制，存在全表扫描风险：$line"
  done <<< "$HITS"
else
  print_ok "DB-15 通过"
fi

echo ""
echo "============================================"
if [[ $ERRORS -gt 0 ]]; then
  echo -e "${RED}❌ 检查完成：$ERRORS 个阻断错误，$WARNINGS 个警告${NC}"
  exit 1
elif [[ $WARNINGS -gt 0 ]]; then
  echo -e "${YELLOW}🟡 检查完成：0 个阻断错误，$WARNINGS 个警告${NC}"
  exit 0
else
  echo -e "${GREEN}✅ 全部通过，无违规项${NC}"
  exit 0
fi
