-- 用户表（PostgreSQL 14+）

-- 1. 建表
CREATE TABLE "user" (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY,   -- 应用层插入雪花ID，DB序列兜底
  name        varchar(64)  NOT NULL,
  phone       varchar(20)  NOT NULL,
  status      smallint     NOT NULL DEFAULT 1,
  created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by  bigint       NOT NULL DEFAULT 0,
  updated_by  bigint       NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

-- 2. 注释
COMMENT ON TABLE  "user"              IS '用户表';
COMMENT ON COLUMN "user".id           IS '主键（雪花ID）';
COMMENT ON COLUMN "user".name         IS '用户名';
COMMENT ON COLUMN "user".phone        IS '手机号';
COMMENT ON COLUMN "user".status       IS '状态：1-正常，0-禁用';
COMMENT ON COLUMN "user".created_at   IS '创建时间';
COMMENT ON COLUMN "user".updated_at   IS '更新时间';
COMMENT ON COLUMN "user".created_by   IS '创建人 userId';
COMMENT ON COLUMN "user".updated_by   IS '更新人 userId';

-- 3. 索引
CREATE UNIQUE INDEX uk_user_phone ON "user" (phone);
CREATE INDEX idx_user_status ON "user" (status);

-- 4. updated_at 表级兜底触发器（必须）
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_user_updated_at
BEFORE UPDATE ON "user"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
