export const THEME = {
  normal: { fg: 'whiteBright' },
  border: { fg: 'gray' },
  borderActive: { fg: 'cyanBright', bold: true },
  title: { fg: 'cyanBright', bold: true },
  muted: { fg: 'gray' },
  selected: { fg: 'black', bg: 'cyanBright', bold: true },
  easy: { fg: 'greenBright' },
  medium: { fg: 'yellowBright' },
  hard: { fg: 'redBright' },
  success: { fg: 'greenBright', bold: true },
  warning: { fg: 'yellowBright', bold: true },
  error: { fg: 'redBright', bold: true },
  overlay: { fg: 'whiteBright', bg: 'black' },
  editorLineNumber: { fg: '#596275' },
  editorLineNumberActive: { fg: '#82aaff', bold: true },
  editorCursor: { inverse: true, bold: true },
  syntax: {
    builtin: { fg: '#82aaff' },
    comment: { fg: '#697098', italic: true },
    function: { fg: '#89ddff' },
    indent: { fg: '#3b4252', dim: true },
    keyword: { fg: '#c792ea', bold: true },
    number: { fg: '#f78c6c' },
    operator: { fg: '#89ddff' },
    string: { fg: '#c3e88d' },
  },
} as const
